// Generated by https://quicktype.io

export interface IDomain {
  domains: Domain[];
  links: IDomainLinks;
}

export interface Domain {
  description: string;
  enabled: boolean;
  id: string;
  links: DomainLinks;
  name: string;
  tags: string[];
}

export interface DomainLinks {
  self: string;
}

export interface IDomainLinks {
  next: null;
  previous: null;
  self: string;
}
