// Generated by https://quicktype.io

export interface IRecDomainScoped {
  token: Token;
}

export interface Token {
  domain: IdName;
  methods: string[];
  roles: IdName[];
  expires_at: string;
  catalog: Catalog[];
  user: User;
  audit_ids: string[];
  issued_at: string;
}

export interface Catalog {
  endpoints: Endpoint[];
  type: string;
  id: string;
  name: string;
}

export interface Endpoint {
  region_id: string;
  url: string;
  region: string;
  interface: InterfaceName;
  id: string;
}

export enum InterfaceName {
  Admin = 'admin',
  Internal = 'internal',
  Public = 'public'
}



export interface IdName {
  id: string;
  name: string;
}

export interface User {
  password_expires_at: null;
  domain: IdName;
  id: string;
  name: InterfaceName;
}
// Generated by https://quicktype.io

export interface IError {
  error: Error;
}

export interface Error {
  message: string;
  code: number;
  title: string;
}
