// Generated by https://quicktype.io

export interface IUser {
  users: User[];
  links: IUserLinks;
}

export interface IUserLinks {
  self: string;
  previous: null;
  next: null;
}

export interface User {
  password_expires_at: null;
  name: string;
  links: UserLinks;
  domain_id: string;
  enabled: boolean;
  id: string;
  options: Options;
  default_project_id?: string;
  email?: string;
}

export interface UserLinks {
  self: string;
}

export interface Options {}
